version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9001:9000
    #networks:
    #  - portainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ildefonso/data/portainer/:/data
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constrainst:
      #    - node.labels.server == evoluum-server
#networks:
#  portainer-net: