version: '3'

services:
  postgres:
    image: postgres
    container_name: postgresapp
    ports:
     - 5432:5432
    environment:
     POSTGRES_PASSWORD: root
    volumes:
     - ./banco_dados/data/postgres:/var/lib/postgresql